name: altfire_lints
description: altfire_lints is helpful in preventing common issues with wrapper packages for flutterfire.
version: 0.1.2
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/issues?q=is%3Aopen+is%3Aissue+label%3Aaltfire_lints

false_secrets:
  - example/**

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  analyzer: ^7.4.5
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  altive_lints: ^1.20.0
  custom_lint: ^0.7.5
