name: altfire_lints
description: altfire_lints is helpful in preventing common issues with wrapper packages for flutterfire.
version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.7

dev_dependencies:
  altive_lints: ^1.9.0
  