name: altfire_authenticator
description: |
  Provides a wrapper class for FlutterFire Authentication package to simplify its usage.
version: 0.1.6
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/labels/altfire_authenticator

false_secrets:
  - example/**

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
