name: altfire_authenticator
description: altfire_authenticator with FlutterFire Authentication.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter
