name: altfire_authenticator
description: |
  altfire_authenticator is a package wrapping FlutterFire Authentication.
  It was created to make Firebase SDK versioning and methods easier to use.
  It is recommended to use the various altfire packages as a set.
version: 0.1.0
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/issues?q=is%3Aopen+is%3Aissue+label%3Aaltfire_authenticator

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter
