include: package:altive_lints/altive_lints.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "lib/firebase_options.dart"
custom_lint:
  rules:
    - avoid_hardcoded_color: false
linter:
  rules:
    public_member_api_docs: false
