name: example
description: "altfire example app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  altfire_authenticator:
    path: ../packages/altfire_authenticator
  altfire_configurator:
    path: ../packages/altfire_configurator
  altfire_messenger:
    path: ../packages/altfire_messenger
  altfire_tracker:
    path: ../packages/altfire_tracker
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints:
    path: ../packages/altfire_lints
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
