# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/example"
      - "/packages/*"
      - "/packages/*/example"
    schedule:
      interval: "weekly"
    groups:
      altfire-dependencies:
        patterns:
          - "altfire_*"
      firebase-dependencies:
        patterns:
          - "firebase_*"
      dependencies-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
