# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_authenticator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_authenticator/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_configurator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_configurator/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_lints"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_lints/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_lints_test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_lints_test/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_messenger"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_messenger/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_tracker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/altfire_tracker/example"
    schedule:
      interval: "weekly"
