name: altfire
repository: https://github.com/altive/altfire

packages:
  - packages/**
  - example

command:
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: ^3.0.0
    dependencies:
      firebase_analytics: ^11.3.5
      firebase_auth: ^5.3.3
      firebase_core: ^3.8.0
      firebase_crashlytics: ^4.1.5
      firebase_crashlytics_platform_interface: ^3.6.46
      firebase_in_app_messaging: ^0.8.0+10
      firebase_messaging: ^15.1.5
      firebase_performance: ^0.10.0+10
      firebase_remote_config: ^5.1.5
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
  version:
    workspaceChangelog: false

scripts:
  custom_lint:
    exec: dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dependsOn: "custom_lint"

  # Issue on file exclusion feature: https://github.com/dart-lang/dart_style/issues/864
  # NOTE: Using the `exec:` format causes processing to stop
  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib/
    description: Run dart format for CI.
    packageFilters:
      dirExists: lib

  fix:
    exec: dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      failFast: true
    description: Run flutter test.
    packageFilters:
      dirExists: test

  test:ci:
    run: flutter test --coverage
    exec:
      failFast: true
    description: Run flutter test for CI.
    packageFilters:
      dirExists: test

  pod:
    description: Run all pod install.
    steps:
      - pod:ios
      - pod:macos

  pod:ios:
    description: Run pod install on iOS.
    exec: cd ios && rm -f Podfile.lock && pod install --repo-update
    packageFilters:
      dirExists: [lib, ios]
      fileExists: "ios/Podfile"

  pod:macos:
    description: Run pod install on macOS.
    exec: cd macos && rm -f Podfile.lock && pod install --repo-update
    packageFilters:
      dirExists: [lib, macos]
      fileExists: "macos/Podfile"
