name: altfire
repository: https://github.com/altive/altfire

packages:
  - packages/**
  - example

command:
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: ^3.0.0
    dependencies:
      collection: ^1.18.0
      firebase_analytics: ^10.10.4
      firebase_auth: ^4.19.4
      firebase_core: ^2.30.1
      firebase_crashlytics: ^3.5.4
      firebase_in_app_messaging: ^0.7.5+4
      firebase_messaging: ^14.9.1
      firebase_remote_config: ^4.4.4
      meta: ^1.11.0
    dev_dependencies:
      altive_lints: ^1.10.0
      custom_lint: ^0.6.4
      mocktail: ^1.0.3
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
  version:
    workspaceChangelog: false

scripts:
  custom_lint:
    exec: dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dependsOn: "custom_lint"

  # Issue on file exclusion feature: https://github.com/dart-lang/dart_style/issues/864
  # NOTE: Using the `exec:` format causes processing to stop
  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib/
    description: Run dart format for CI.
    packageFilters:
      dirExists: lib

  fix:
    exec: dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      failFast: true
    description: Run flutter test.
    packageFilters:
      dirExists: test

  test:ci:
    run: flutter test --coverage
    exec:
      failFast: true
    description: Run flutter test for CI.
    packageFilters:
      dirExists: test

  pod:
    description: Run all pod install.
    steps:
      - pod:ios
      - pod:macos

  pod:ios:
    description: Run pod install on iOS.
    exec: cd ios && pod install --repo-update
    packageFilters:
      dirExists: [lib, ios]
      fileExists: "ios/Podfile"

  pod:macos:
    description: Run pod install on macOS.
    exec: cd macos && pod install --repo-update
    packageFilters:
      dirExists: [lib, macos]
      fileExists: "macos/Podfile"
