name: altfire
repository: https://github.com/altive/altfire

packages:
  - packages/**
  - example

command:
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: ^3.0.0
    dependencies:
      collection: ^1.18.0
      firebase_analytics: ^10.6.3
      firebase_auth: ^4.10.1
      firebase_core: ^2.21.0
      firebase_crashlytics: ^3.4.3
      firebase_in_app_messaging: ^0.7.4+6
      firebase_messaging: ^14.7.6
      firebase_remote_config: ^4.3.3
      meta: ^1.10.0
    dev_dependencies:
      altive_lints: ^1.9.0
      mocktail: ^1.0.2

  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
  version:
    branch: main

scripts:
  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Run upgrade the major version of the pub.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:
    run: |
      melos run analyze:dart --no-select && \
      melos run analyze:flutter --no-select && \
      melos run analyze:custom_lint --no-select
    description: Run all analyze.
    packageFilters:
      dirExists: lib

  analyze:dart:
    run: |
      melos exec -- \
        dart analyze . --fatal-infos
    description: Run analyze.
    packageFilters:
      flutter: false
      dirExists: lib

  analyze:flutter:
    run: |
      melos exec -- \
        flutter analyze . --fatal-infos
    description: Run analyze.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:custom_lint:
    run: |
      melos exec -- \
        dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dependsOn: "custom_lint"

  format:
    run: |
      melos exec -- \
        dart format lib/
    description: Run dart format.
    packageFilters:
      dirExists: lib

  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib/
    description: Run dart format for CI.
    packageFilters:
      dirExists: lib

  fix:
    run: |
      melos exec -- \
        dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  test:
    run: |
      melos exec --fail-fast -- \
        flutter test
    description: Run flutter test.
    packageFilters:
      dirExists: test

  test:ci:
    run: |
      melos exec --fail-fast -- \
        flutter test --coverage
    description: Run flutter test for CI.
    packageFilters:
      dirExists: test
