name: altfire
repository: https://github.com/altive/altfire

packages:
  - packages/**
  - example

command:
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: ^3.0.0
    dependencies:
      collection: ^1.18.0
      firebase_analytics: ^10.6.3
      firebase_auth: ^4.10.1
      firebase_core: ^2.21.0
      firebase_crashlytics: ^3.4.9
      firebase_in_app_messaging: ^0.7.4+6
      firebase_messaging: ^14.7.6
      firebase_remote_config: ^4.3.3
      meta: ^1.10.0
    dev_dependencies:
      altive_lints: ^1.9.0
      mocktail: ^1.0.2
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean"
  version:
    workspaceChangelog: false

scripts:
  custom_lint:
    exec: dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dependsOn: "custom_lint"

  # Issue on file exclusion feature: https://github.com/dart-lang/dart_style/issues/864
  # NOTE: Using the `exec:` format causes processing to stop
  format:ci:
    run: |
      melos exec -- \
        dart format --set-exit-if-changed lib/
    description: Run dart format for CI.
    packageFilters:
      dirExists: lib

  fix:
    exec: dart fix --apply lib
    description: Run dart fix.
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      failFast: true
    description: Run flutter test.
    packageFilters:
      dirExists: test

  test:ci:
    run: flutter test --coverage
    exec:
      failFast: true
    description: Run flutter test for CI.
    packageFilters:
      dirExists: test
