name: altfire

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^7.0.0-dev.3

workspace:
  - example
  - packages/altfire_authenticator
  - packages/altfire_authenticator/example
  - packages/altfire_configurator
  - packages/altfire_configurator/example
  - packages/altfire_lints
  - packages/altfire_lints_test
  - packages/altfire_messenger
  - packages/altfire_messenger/example
  - packages/altfire_tracker
  - packages/altfire_tracker/example

melos:
  packages:
    - packages/**
  ignore:
    - "packages/**/example"
  command:
    version:
      workspaceChangelog: false
