name: altfire_messenger
description: |
  altfire_messenger is a package wrapping FlutterFire Messaging, Local Notifications, Firebase In-App Messaging, and Firebase Instance ID.
  It was created to make Firebase SDK versioning and methods easier to use.
  It is recommended to use the various altfire packages as a set.
version: 0.1.0
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/issues?q=is%3Aopen+is%3Aissue+label%3Aaltfire_messenger

false_secrets:
  - example/**

environment:
  sdk: ^3.0.0

dependencies:
  firebase_in_app_messaging: ^0.7.5+4
  firebase_messaging: ^14.9.1
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
