name: altfire_messenger
description: |
  Provides a wrapper class for FlutterFire messaging and in_app_messaging packages to simplify its usage.
version: 0.2.1
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/labels/altfire_messenger

false_secrets:
  - example/**

environment:
  sdk: ^3.0.0

dependencies:
  firebase_in_app_messaging: ^0.8.0+8
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ">=17.2.2 <19.0.0"
  timezone: ^0.9.4

dev_dependencies:
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
