// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK_pKdPX1e3q5S-Q0CrtHPs7AH7_wkgUc',
    appId: '1:282061201204:web:724b1f695c81679eb04f61',
    messagingSenderId: '282061201204',
    projectId: 'flutterfire-adapter',
    authDomain: 'flutterfire-adapter.firebaseapp.com',
    storageBucket: 'flutterfire-adapter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QqWrVIJNsh-DOmV4OY4gVAi1jXW4e6s',
    appId: '1:282061201204:android:86708a3c3a298e18b04f61',
    messagingSenderId: '282061201204',
    projectId: 'flutterfire-adapter',
    storageBucket: 'flutterfire-adapter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2cbXfGjFB4EdKJTFojoAt_7wM-P10lg',
    appId: '1:282061201204:ios:6601d34e83ae0bb5b04f61',
    messagingSenderId: '282061201204',
    projectId: 'flutterfire-adapter',
    storageBucket: 'flutterfire-adapter.appspot.com',
    iosBundleId: 'jp.co.altive.flutterfireremoteparameterfetcher.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2cbXfGjFB4EdKJTFojoAt_7wM-P10lg',
    appId: '1:282061201204:ios:1b277bae5641209db04f61',
    messagingSenderId: '282061201204',
    projectId: 'flutterfire-adapter',
    storageBucket: 'flutterfire-adapter.appspot.com',
    iosBundleId: 'jp.co.altive.flutterfireremoteparameterfetcher.example.RunnerTests',
  );
}
