name: altfire_tracker
description: altfire_tracker with FlutterFire Analytics and Crashlytics.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  firebase_analytics: ^10.6.3
  firebase_crashlytics: ^3.4.3
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
