name: altfire_configurator_example
description: Demonstrates how to use the altfire_configurator package.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  altfire_configurator:
  firebase_analytics: ^11.4.6
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints:
  altive_lints: ^1.20.0
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
