name: altfire_configurator_example
description: Demonstrates how to use the altfire_configurator package.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  altfire_configurator:
    path: ../
  firebase_analytics: ^10.10.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints:
    path: ../../altfire_lints
  altive_lints: ^1.10.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
