name: flutterfire_lint_test
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutterfire_configurator:

dev_dependencies:
  altive_lints: ^1.9.0
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  flutterfire_lint:
    path: ../flutterfire_lint

dependency_overrides:
  flutterfire_configurator:
    path: ../flutterfire_configurator