name: flutterfire_configurator
description: flutterfire_configurator with FlutterFire Remote Config.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  firebase_remote_config: ^4.3.3
  meta: ^1.10.0

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter