name: flutterfire_configurator
description: flutterfire_configurator with FlutterFire Remote Config.
version: 0.1.0
homepage: https://altive.dev
repository: https://github.com/altive/flutterfire_adapter
issue_tracker: https://github.com/altive/flutterfire_adapter/issues

environment:
  sdk: ^3.0.0

dependencies:
  firebase_remote_config: ^4.3.3
  meta: ^1.10.0

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter