name: flutterfire_notification
description: flutterfire_notification with FlutterFire Messaging, Local Notifications and In-App Messaging, and Firebase Instance ID.
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.8.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
