name: altfire_configurator
description: |
  altfire_configurator is a package wrapping FlutterFire Remote Config.
  It was created to make Firebase SDK versioning and methods easier to use.
  It is recommended to use the various altfire packages as a set.
version: 0.1.1
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/issues?q=is%3Aopen+is%3Aissue+label%3Aaltfire_configurator

false_secrets:
  - example/**

environment:
  sdk: ^3.0.0

dependencies:
  firebase_remote_config: ^5.0.2
  meta: ^1.12.0

dev_dependencies:
  altive_lints: ^1.10.0
  flutter_test:
    sdk: flutter