name: altfire_configurator
description: |
  Provides a wrapper class for the FlutterFire RemoteConfig package to simplify its usage.
version: 1.0.0
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/labels/altfire_configurator

false_secrets:
  - example/**

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  firebase_remote_config: ^5.4.4
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  altive_lints: ^1.20.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
