name: altfire_configurator
description: |
  Provides a wrapper class for the FlutterFire RemoteConfig package to simplify its usage.
version: 0.1.4
homepage: https://altive.dev
repository: https://github.com/altive/altfire
issue_tracker: https://github.com/altive/altfire/labels/altfire_configurator

false_secrets:
  - example/**

environment:
  sdk: ^3.0.0

dependencies:
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  altive_lints: ^1.10.0
  flutter_test:
    sdk: flutter
