name: altfire_tracker_example
description: "Demonstrates how to use the altfire_tracker package. "
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  altfire_tracker:
    path: ../
  dio: ^5.4.0
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  altive_lints: ^1.9.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
