name: altfire_tracker_example
description: "Demonstrates how to use the altfire_tracker package. "
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  altfire_tracker:
    path: ../
  dio: ^5.4.3+1
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.10.0
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
