name: altfire_authenticator_example
description: "Demonstrates how to use the altfire_authenticator package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  altfire_authenticator:
    path: ../
  build_runner: ^2.4.8
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
