name: altfire_authenticator_example
description: "Demonstrates how to use the altfire_authenticator package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  altfire_authenticator:
    path: ../
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
