name: altfire_authenticator_example
description: "Demonstrates how to use the altfire_authenticator package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  altfire_authenticator:
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.20.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
