name: altfire_messenger_example
description: "Demonstrates how to use the altfire_messenger package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  altfire_messenger:
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.20.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
