name: altfire_messenger_example
description: "Demonstrates how to use the altfire_messenger package."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  altfire_messenger:
    path: ../
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
