name: altfire_lints_test
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  altfire_configurator:
    path: ../altfire_configurator
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints:
    path: ../altfire_lints
  altive_lints: ^1.10.0
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
