name: altfire_lints_test
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  altfire_configurator:
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints:
    path: ../altfire_lints
  altive_lints: ^1.9.0
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter

dependency_overrides:
  altfire_configurator:
    path: ../altfire_configurator