name: altfire_lints_test
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  altfire_configurator: any
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints: any
  altive_lints: ^1.16.0
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
