name: altfire_lints_test
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  altfire_configurator: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  altfire_lints: ^1.0.0
  altive_lints: ^1.20.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
