name: flutterfire_authenticator
description: flutterfire_authenticator with FlutterFire Authentication.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  altive_lints: ^1.8.1
  flutter_test:
    sdk: flutter
