name: code check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      flutter: ${{ steps.filter.outputs.flutter }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter by paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter:
              - '**/android/**'
              - '**/assets/**'
              - '**/dart_defines/**'
              - '**/golden_test/**'
              - '**/ios/**'
              - '**/lib/**'
              - '**/test/**'
              - '**/web/**'
              - '**/analysis_options.yaml'
              - '**/pubspec.yaml'

  analyze:
    needs: check
    if: ${{ needs.check.outputs.flutter == 'true' && github.event_name != 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

  test:
    needs: check
    if: needs.check.outputs.flutter == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: |
          if test -d "test"; then
            if grep -q flutter "pubspec.yaml"; then
              flutter test --coverage
            else
              dart pub global activate coverage
              dart pub global run coverage:test_with_coverage
            fi
          fi
      - name: Upload coverage to codecov
        run: |
          if test -d "test"; then
            curl -s https://codecov.io/bash | bash
          fi
