name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      scope:
        description: >
          Select a package to release (optional).
          If not selected, only packages with changes will be included.
        required: false
        type: choice
        options:
          - altfire_authenticator
          - altfire_configurator
          - altfire_lints
          - altfire_lints_test
          - altfire_messenger
          - altfire_tracker

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      changed_packages: ${{ steps.get-changed-packages.outputs.packages }}
      branch_name: ${{ steps.set-branch-name.outputs.branch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Melos
        run: melos bootstrap

      - name: Run `melos version`
        id: get-changed-packages
        env:
          MELOS_ALLOW_DIRTY: "true"
        run: |
          if [[ -n "${{ github.event.inputs.scope }}" ]]; then
            melos version --patch --no-private --yes --scope="${{ github.event.inputs.scope }}"
          else
            melos version --patch --no-private --yes
          fi

          CHANGED_PACKAGES=$(git diff --name-only | grep "packages/.*/pubspec.yaml" | cut -d '/' -f2 | sort | uniq)

          if [[ -z "$CHANGED_PACKAGES" ]]; then
            echo "No package changes detected."
            exit 0
          fi

          echo "packages=$CHANGED_PACKAGES" >> "$GITHUB_OUTPUT"

      - name: Set branch name
        id: set-branch-name
        run: |
          BRANCH_NAME="release/$(date +"%Y-%m-%d")"
          echo "branch=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

  create-branch:
    name: Create release branch
    runs-on: ubuntu-latest
    needs: [prepare-release]
    env:
      branch: ${{ needs.prepare-release.outputs.branch_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Check if branch already exists
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.branch }}; then
            echo "branch_exists=true" >> "$GITHUB_ENV"
          else
            echo "branch_exists=false" >> "$GITHUB_ENV"
          fi

      - name: Create release branch
        if: env.branch_exists == 'false'
        run: |
          git switch -c ${{ env.branch }}
          git push origin ${{ env.branch }}

  create-pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    needs: [prepare-release, create-branch]
    if: needs.prepare-release.outputs.changed_packages != ''
    permissions:
      contents: write
      pull-requests: write
    env:
      branch: ${{ needs.prepare-release.outputs.branch_name }}
      packages: ${{ needs.prepare-release.outputs.changed_packages }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app-id }}
          private-key: ${{ secrets.private-key }}

      - name: Create release PR
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          PR_TITLE="chore(release): publish packages"
          PR_BODY="This pull request updates the following packages:\n\n"
          for PACKAGE in $packages; do
            VERSION=$(grep -m 1 'version:' packages/$PACKAGE/pubspec.yaml | awk '{print $2}')
            PR_BODY+=" - \`$PACKAGE\`: \`$VERSION\`\n"
          done

          echo "Creating PR with title: $PR_TITLE"
          gh pr create -B "main" -H "$branch" -t "$PR_TITLE" -b "$PR_BODY" -a "$GITHUB_ACTOR"