name: Publish to pub.dev

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/'))
    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: Get dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          echo "$PUB_CREDENTIALS" > "$HOME/.config/dart/pub-credentials.json"
          melos publish --no-dry-run --yes
